### ISSUE TITLE
Allow selecting the knowledge bases used in task processing during runtime

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#10]
Only single knowledge base for the 1st iteration.

Requirement 47.

**Comment by brodecva** [comment]
Obsolete.

**Comment by tomas-knap** [comment]
THis is something we would like to have in iter4 (at the level of config file). @brodecva, please plan or link to existing duplicate issue.

**Comment by brodecva** [comment]
> THis is something we would like to have in iter4 (at the level of config file). @brodecva, please plan or link to existing duplicate issue.

Duplicates #224.
