### ISSUE TITLE
Test the general SPARQL support by running the algorithm against any other SPARQL-based KB

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#108]
Add a test case, if possible.

**Comment by tomas-knap** [comment]
To test any other SPARQL based repo, you may use e.g.: 
- german version of DBpedia: http://de.dbpedia.org/sparql
- dbpedia live: http://dbpedia-live.openlinksw.com/sparql/

Do not spend much time on that, the motivation is to basically test that:
1) SPARQL based repositories may be defined
2) multiple KB work reasonably

**Comment by brodecva** [comment]
Jan works on Wikidata now.

**Comment by brodecva** [comment]
Let's wrap this up: what is the state of this, @JanVana ? Can we verify that the algorithm can run on other SPARQL based KB other than DBpedia without extensive modifications?

**Comment by tomas-knap** [comment]
Would suggest to close this as it was tested against 2 KBs
