### ISSUE TITLE
Process correctly RDF data within JSON metadata

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#118]
When creating JSON metadata for the extended CSV file, currently, we use hard coded properties "rdf:type" and "dcterms:title". But this is not correct approach. 

We should use JSON-LD standard to define prefixes for predicates (https://www.w3.org/TR/json-ld/#dfn-prefix). RDF exporting component should then NOT try to find strings "dcterms:title", but should use rdf4j to extract model for the JSON metadata document and should use that to get URLs for the used predicated. 

Tasks:
adjust components producing JSON metadata and RDF export components (Pepa) so that used prefixes are correctly introduced.

**Comment by tomas-knap** [comment]
@josef-janousek Do you know where the problem is? What I meant with the issue description?

**Comment by tomas-knap** [comment]
Cil je, aby 1) v tom JSON Annotated file nebyly nedefinovane prefixy typu "dcterms", 2) aby v tom vystupni JSON-LD RDF formatu byly URI spravne, tj. bud full URI (co je myslim ted) a nebo prefixy, ale take s definici co ty prefixy zastupuji na zacatku.

**Comment by tomas-knap** [comment]
@josef-janousek  So this is adjusted and ready for testing?

**Comment by josef-janousek** [comment]
@tomas-knap Yes, it is.

**Comment by tomas-knap** [comment]
Tested, it is OK
