### ISSUE TITLE
Implement methods of the Task service

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#12]
Implement the methods of #5. Consider result of #41.

**Comment by brodecva** [comment]
Please do the file service implementation first. I have not yet finished laying out the basic structure of the Task REST API. I will do so today and will notify you when done.

**Comment by istvan-satmari** [comment]
Request to "push task" => response should already contain the necessary result.
This is only because we want to omit "polling".

**Comment by istvan-satmari** [comment]
Please follow the specification stored on "grips.semantic-web.at" regarding the REST API. Thanks.

**Comment by brodecva** [comment]
I have finalized the design of the API for the 1st iteration. I will update the specification tomorrow with all available calls and formats of provided data.
I will do some basic tests to verify the API works correctly and then I'll pack you the .war for István.
