### ISSUE TITLE
Wrong class/disambiguation dialogs when one KB is used

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#131]
_From @tomas-knap on August 30, 2016 10:9_

When running Odalic against one kb (Dbpedia), using the conf as in config/Jan, but specifying only DBPedia knowledge base, when the task result is available and I open details of classification/disambiguation, I got: 

![screen shot 2016-08-30 at 12 06 21](https://cloud.githubusercontent.com/assets/3014917/18085165/3bd28a98-6eaa-11e6-9300-b464d54cbeab.png)

![screen shot 2016-08-30 at 12 06 14](https://cloud.githubusercontent.com/assets/3014917/18085167/4135a7fe-6eaa-11e6-840d-d498ebc8f239.png)

Problem: In that case I should see only one KB textarea - DBPedia. It is automatically also considered to be primary KB.

_Copied from original issue: odalic/odalic-ui#60_

**Comment by brodecva** [comment]
_From @tomas-knap on August 30, 2016 10:43_

Also please check if it behaves correctly when you try to create new edge in Step 3 - relations - if the dialog looks the same as in case of classification/disambiguation. Currently it looks as follows: 

![screen shot 2016-08-30 at 12 43 28](https://cloud.githubusercontent.com/assets/3014917/18086284/722ca95c-6eaf-11e6-974c-983f660646fc.png)

**Comment by brodecva** [comment]
@tomas-knap As the KB listing and managing API is not yet established. Odalic UI uses hard-coded name of the primary KB and it is "DBpedia". Jan's configuration misspells it as "DBPedia" with capital P.

@JanVana Please fix this typo and also prune the config folder to contain only one set of config files with sensible values. (you can leave there those, that belong to the original TM+ batches, although we will probably get rid of them later).

**Comment by brodecva** [comment]
> Also please check if it behaves correctly when you try to create new edge in Step 3 - relations - if the dialog looks the same as in case of classification/disambiguation. Currently it looks as follows: 

@tomas-knap I believe this is correct as this appears in the direction where TM+ does not find any relations (in the opposite it does and the UI then displays the alternatives) so the UI cannot provide you with any suggestions when you try to create a new one. It could look more pleasing though (without that ugly grey rectangle highlighting nothing), I will create an issue for that, for the next iterations, if you don't mind.

**Comment by brodecva** [comment]
@tomas-knap Also please consider reporting two and more problems in separate issues. It makes the processing easier and clearer to bystanders, especially in this case, when I had to move the issue to another repository. Thank you.

**Comment by tomas-knap** [comment]
Thanks for updates. 
Will do that ;)

**Comment by JanVana** [comment]
The configs are pruned and the typo is fixed in branch 131_Configs. There are three KBs configured now. Two DBpedia instances and one German DBpedia.

**Comment by brodecva** [comment]
> the typo is fixed

Haha I think you missed it again. I fixed it myself in the #136 pull request.

Otherwise great job, closing.
