### ISSUE TITLE
Investigate if comma is properly escaped when searching KBs

### ISSUE THREAD

**Issue by JanVana** [odalic/sti#135]
There might be an issue with comma escaping in SPARQL queries. Test file that causes the problem is mentioned in the issue #132.

**Comment by JanVana** [comment]
Regex and SPARQL escaping was added to the KB search. Regex is still problematic and slow and times out for complicated queries. For this reason, I have added support for the Virtuoso specific fulltext search.

**Comment by brodecva** [comment]
Tested and it seems to work well.
