### ISSUE TITLE
JAXB errors in the logs

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#141]
Hi, could you please send me a complete log or better verify first that these do happen in the latest develop version?
I could not reproduce these.

**Comment by tomas-knap** [comment]
See https://github.com/odalic/sti/issues/151#issue-175249768

Probably connected with use of Chrome. Does not occur in Safari.

**Comment by brodecva** [comment]
Thank you. I was able to reproduce the issue in Chrome. Something in Chrome causes the JAXB to be less tolerant to errors in annotations. I fixed the causes.
