### ISSUE TITLE
Support leaving a column from the export

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#142]
Story at https://grips.semantic-web.at/x/sBZsB . From all kinds (RDF, CSV, annotations,...).

**Comment by brodecva** [comment]
Hi, @josef-janousek , I have discovered this forgotten feature. Feel free to implement it when you are bored with the tests.

**Comment by tomas-knap** [comment]
Related: https://github.com/odalic/odalic-ui/issues/70 was moved to 5th iter. @brodecva, move also this?

**Comment by brodecva** [comment]
> Related: odalic/odalic-ui#70 was moved to 5th iter. @brodecva, move also this?

OK. @josef-janousek Ignore this until the 5th iteration.
