### ISSUE TITLE
No labels in relation concepts

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#150]
The Book.csv does not return any labels for the relation concepts. Is that a correct behaviour?

**Comment by brodecva** [comment]
The labels are missing in the TableMinder+ result. Nothing is lost in our conversions.

**Comment by brodecva** [comment]
LodLive seems to provide label for "surname" for example, so I suspect that there indeed is some error in the core.

**Comment by tomas-knap** [comment]
There should be some label in dbpedia. Maybe the predicates in which the label is searched for are incorrectly set up?

**Comment by brodecva** [comment]
Please, @JanVana , fix it as soon as possible.

**Comment by JanVana** [comment]
This will be more complicated than a simple bug fix. As of now, the core algorithm does not search for relation labels and does not event expect to receive labels from the KB search package.

**Comment by tomas-knap** [comment]
@brodecva, Jan may look on that when search/propose issues are done.

**Comment by tomas-knap** [comment]
Possible solutions: 
* Adjust KBSearch algo
* Simple service na backendu, ktera ziska name tak, ze dereferencuje URL a vrati label/title?

@brodecva @JanVana What was the decided approach? Or which one do you recommend?

**Comment by brodecva** [comment]
@JanVana @tomas-knap To be honest, I see no reason to not make the algorithm work the propert way and fetch the labels for properties as well.

**Comment by JanVana** [comment]
This issue is implemented in the pull request #348.
