### ISSUE TITLE
Support cross origin requests to the API

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#155]

**Comment by brodecva** [comment]
This usually requires some collaboration between the client and server, so let's add @istvan-satmari to the assigned.

**Comment by tomas-knap** [comment]
@brodecva  was it solved or is it won't fix?

**Comment by brodecva** [comment]
> was it solved or is it won't fix?

@tomas-knap The solution was present since the beginning, but only during the authorization feature testing it was proven that it actually works (as @istvan-satmari needed to add Authorization header to the list of allowed across origins).

Sorry about the missing report.
