### ISSUE TITLE
Column classification is wrong: It uses predicates to classify columns

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#159]
Develop branch as of 7.9. Testing file: 
[Books-v1.csv.zip](https://github.com/odalic/odalic-ui/files/463889/Books-v1.csv.zip), the classification for "series" is wrong

For the "series" column,

![screen shot 2016-09-09 at 14 10 58](https://cloud.githubusercontent.com/assets/3014917/18386423/44d94c68-7697-11e6-974c-47afe77ab438.png)

 I got: 

![screen shot 2016-09-09 at 14 03 12](https://cloud.githubusercontent.com/assets/3014917/18386351/d0c815de-7696-11e6-993d-9c78451b49d9.png)

But these suggested resources are predicates, not classes. SO they may appear in Step 3 (where relations are suggested), but not in Step 2 (where we are looking for the classes). 

In general: Classification (Step 2) must not use predicates as resources classifying the columns

Note: To recognize predicate, it is instance of rdf:Property

**Comment by JanVana** [comment]
The full DBpedia returns Category, but the limited DBpedia returns the correct DBpedia link. Why?

**Comment by JanVana** [comment]
@brodecva I have finally completed the refactoring of SPARQL queries and added the restriction to exclude properties from the search. But I am getting some weird server error with no information in the log. All the test executions are working, are there any problems with the tasks currently?

**Comment by brodecva** [comment]
@JanVana Everything works just fine for me, even after merging your contribution.

**Comment by tomas-knap** [comment]
@JanVana So what was the root cause of that issue?

**Comment by JanVana** [comment]
@tomas-knap There was no restriction on the type of the searched items before. I have added one, so the query looks like this now:

SELECT DISTINCT ?Subject WHERE
{
  ?Subject rdfs:label ?Label .
  ?Label bif:contains '"Steven Erikson"' .
  ?Subject a ?Class .
  ?Class a owl:Class .
}

**Comment by tomas-knap** [comment]
Ok, but please make it customizable (the part: ?Class a owl:Class), so that it reads from the KB which resource is used for expressing "a class". I think there is such a property in the KB already, right? In most cases it is "owl:Class", but could be also just "skos:Concept" in certain cases.

**Comment by tomas-knap** [comment]
If it is already done in that way, please ignore

**Comment by JanVana** [comment]
Class, label and bif:contains are all customizable in the current version. The rdf type is not, but it could be done.
