### ISSUE TITLE
Configuration import/export

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#163]
Stories at https://grips.semantic-web.at/x/I4F2B and https://grips.semantic-web.at/x/JYF2B.

**Comment by tomas-knap** [comment]
Could be also iter5

**Comment by brodecva** [comment]
Joining with import, removing @istvan-satmari , as I will create a separate task for the UI.

**Comment by tomas-knap** [comment]
Please till 6.2. latest.

**Comment by brodecva** [comment]
Finished in #361 .
