### ISSUE TITLE
Processing starts even when the headers count does not match the columns count

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#169]

**Comment by tomas-knap** [comment]
In this case I would suggest to simply report error (cannot be process, number of header does not correspond to number of columns)

**Comment by josef-janousek** [comment]
Now user can see that the error was caused by CSV file inconsistency:
![inconsistency](https://cloud.githubusercontent.com/assets/17772934/21119984/5bdfe08e-c0c5-11e6-845a-14249b88b414.png)
