### ISSUE TITLE
Add prefixes to (similar) labels

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#171]
E.g. "http://dbpedia.org/ontology/series" and  "http://dbpedia.org/property/series" are indistinguishable by a label. A prefix to the labels must be somehow derived or set in configuration (per KB).

**Comment by tomas-knap** [comment]
Would suggest to introduce new config file for Odalic, which may contain list of namespace prefixes and URLs, which are valid for all knowledge bases. Question is in which format this list should be provided. If we go for persisting task configuration into RDF format, I would strongly recommend to go for some RDF config as well (it should be pretty straightforward anyway)

**Comment by brodecva** [comment]
Waits for https://github.com/odalic/sti/issues/322 .

**Comment by brodecva** [comment]
#330 adds provides the client with prefix for every entity. From now the entity object sent from the server contains also "prefix" and "tail" fiels. Prefix field is an object containing "with" (the actual prefix string) and "what" (associated URI) attributes. Tail is what is left of the expanded resource URI after the prefix separator.

**Comment by brodecva** [comment]
Closing. The UI part is dealt with in https://github.com/odalic/odalic-ui/issues/92 .
