### ISSUE TITLE
Installation guide update

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#172]
Based on https://docs.google.com/document/d/1I6wm8-BKj0lS4KJJEYDbXroTiovauyT4J4JPsLPdfQo/edit .

Notify the newly associated colleague when done.

**Comment by brodecva** [comment]
Until the end of this week!

**Comment by tomas-knap** [comment]
Please put it into: https://grips.semantic-web.at/display/ADEQ/Installation+Guide
