### ISSUE TITLE
Number of new babies by the cities, districts

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#175]
https://grips.semantic-web.at/x/sASBB

**Comment by tomas-knap** [comment]
10lines : 
[STMK_2012_LIVEBIRTHS-10lines.csv.zip](https://github.com/odalic/sti/files/622142/STMK_2012_LIVEBIRTHS-10lines.csv.zip)

Result:
![screen shot 2016-11-30 at 16 25 37](https://cloud.githubusercontent.com/assets/3014917/20758341/c49b814c-b719-11e6-9cd4-57dcfc4f9a48.png)

To be discussed/look into: 
- 

Full file:

**Comment by josef-janousek** [comment]
Version: develop 11.12.2016
File: http://service.stmk.gv.at/ogd/OGD_Data_ABT17/statistik/STMK_2012_LIVEBIRTHS.csv (reduced to 20 lines)

Result - against Jan's (reduced) DBpedia, original DBpedia and German DBpedia):
![stmk_2012_livebirths_result](https://cloud.githubusercontent.com/assets/17772934/21079939/0699fcbe-bfa2-11e6-9b6b-d3112fade5c1.png)

![stmk_2012_livebirths_relations](https://cloud.githubusercontent.com/assets/17772934/21079940/1711e516-bfa2-11e6-91a5-04f3f1b87ac9.png)

Classification:
- NUTS1 not; NUTS2 only DBpedia, but strange (Item); NUTS3 only German DBpedia, but without label
- DISTRICT_NAME all, but only DBpedia seems correct (District)
- LAU_NAME all, but strange, just reduced DBpedia seems better (Settlement)
- DISTRICT_CODE, LAU_CODE, LIVEBIRTHS and YEAR not (expected, just numeric values)

Disambiguation:
- NUTS1 all seems OK; NUTS2 only DBpedia, but seems strange; NUTS3 nothing
- DISTRICT_NAME mostly all seems OK, just Graz-Stadt seems strange
- LAU_NAME sometimes all OK, sometimes just German DBpedia, sometimes nothing
- DISTRICT_CODE, LAU_CODE, LIVEBIRTHS and YEAR are just numeric values

Subject column:
- LAU_NAME always - seems OK

Relations:
- LAU_NAME -> DISTRICT_NAME (district) seems OK (except German DBpedia)
- LAU_NAME -> NUTS3 (nutsCode) only in German DBpedia, but not correct

Other:
- Special German characters, e.g. ß, not correctly displayed

Complete data (original and reduced file, screens and exports) attached:
[STMK_2012_LIVEBIRTHS.zip](https://github.com/odalic/sti/files/644428/STMK_2012_LIVEBIRTHS.zip)

**Comment by tomas-knap** [comment]
Maintained at https://grips.semantic-web.at/display/ADEQ/Number+of+new+babies+by+the+cities%2C+districts
