### ISSUE TITLE
Table of States

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#177]
https://grips.semantic-web.at/x/sASBB

**Comment by josef-janousek** [comment]
Version: develop 11.12.2016
File: http://www.wien.gv.at/statistik/ogd/vie_001.csv (reduced to 10 lines)
Preprocessing: Remove extra first row

Result - against Jan's (reduced) DBpedia, original DBpedia and German DBpedia:
![states_result1](https://cloud.githubusercontent.com/assets/17772934/21081354/f187338c-bfc4-11e6-8dda-bd49e041d61e.png)
![states_result2](https://cloud.githubusercontent.com/assets/17772934/21081355/f64e954a-bfc4-11e6-89ad-328bd1ba41ba.png)

![states_relations](https://cloud.githubusercontent.com/assets/17772934/21081356/fdb0be3a-bfc4-11e6-8b99-dcf5c6261281.png)

Classification:
- mostly not correct enough

Disambiguation:
- not displayed in UI

Subject column:
- NAME_GER always - seems good

Relations:
- mostly not correct enough

Other:
- UI - result - first step: only header is displayed, data rows are not displayed

Complete data (original and reduced file, screens, exports and caches) attached:
[states.zip](https://github.com/odalic/sti/files/644570/states.zip)

**Comment by tomas-knap** [comment]
Covered by https://github.com/odalic/sti/issues/288
