### ISSUE TITLE
Schools in Wien

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#181]
https://grips.semantic-web.at/x/sASBB

**Comment by josef-janousek** [comment]
Version: develop 11.12.2016
File: http://data.wien.gv.at/daten/geo?service=WFS&request=GetFeature&version=1.1.0&typeName=ogdwien:SCHULEOGD&srsName=EPSG:4326&outputFormat=csv

- Note: The original file uses commas as separators of values (and text fields are wrapped in quotes). Currently the program is not prepared for this file configuration, so rows are not split to columns and no results are found:
![schulen_result](https://cloud.githubusercontent.com/assets/17772934/21082662/6a49d246-bfe0-11e6-9df7-7f9acad9e1f3.png)

**Comment by tomas-knap** [comment]
Covered by https://github.com/odalic/sti/issues/288
