### ISSUE TITLE
Number of dogs (according to breeds) in the city of Vienna

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#182]
https://grips.semantic-web.at/x/sASBB

**Comment by josef-janousek** [comment]
Version: develop 11.12.2016
File: https://www.wien.gv.at/finanzen/ogd/hunde-wien.csv
Preprocessing: Remove extra header line

Result - against Jan's (reduced) DBpedia, original DBpedia and German DBpedia:
![hunde-wien_result](https://cloud.githubusercontent.com/assets/17772934/21082824/c084c118-bfe3-11e6-9e6d-9a7f74b81262.png)

Classification:
- NUTS1 not; NUTS2 only DBpedia, but strange (Item); NUTS3 not
- Dog Breed all: DBpedia seems correct (Breed / dog breed), but German DBpedia not correct (Location)
- other columns not (expected, just numeric values)

Disambiguation:
- NUTS1 all seems OK; NUTS2 only DBpedia, but seems strange; NUTS3 nothing
- Dog Breed sometimes all OK, sometimes just German DBpedia, sometimes two of KBs, sometimes nothing
- other columns are just numeric values

Subject column:
- Dog Breed always - OK

Relations:
- no relations were found

Other:
- Special characters, e.g. é, not correctly displayed

Complete data (original and reduced file, screens, exports and caches) attached:
[hunde-wien.zip](https://github.com/odalic/sti/files/644750/hunde-wien.zip)

**Comment by tomas-knap** [comment]
Covered by https://github.com/odalic/sti/issues/288
