### ISSUE TITLE
"Description" in task edit is not supported

### ISSUE THREAD

**Issue by istvan-satmari** [odalic/sti#200]
Currently REST API does not support "description" field when reconfiguring a task.
URL of the request:
PUT http://example.com/tasks/simple_task/configuration

Accepts data only in this format:
{ "input": "file description ID", feedback: { ... }, "primaryBase": { "name": "DBpedia" } }

i.e. there is no 'description'.

**Comment by brodecva** [comment]
> Currently REST API does not support "description" field when reconfiguring a task.
> URL of the request:
> PUT http://example.com/tasks/simple_task/configuration
> 
> Accepts data only in this format:
> { "input": "file description ID", feedback: { ... }, "primaryBase": { "name": "DBpedia" } }
> 
> i.e. there is no 'description'.

Hi, this is not a bug, but a result of confusion.

The task itself has a following structure:
`{
   "id": "complex task",
   "description": "Muhaha",
   "created": "2016-11-14 21:34",
   "configuration": {
      "input": "books.csv",
      "feedback": {...},
      "primaryBase": {
      "name": "DBPedia"
   }
}`

What you attempted to put was the configuration, but the description is located in the task object, not in the configuration object.
