### ISSUE TITLE
When entity searched, added and chosen as another classification entity, the original chosen is not among chosen in the next run

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#202]
_From @brodecva on November 16, 2016 16:8_

The feedback sent by the client seems to be OK, so it must be the algorithms (meaning the constraints processing) fault.
True, I have set a resource (Hugo Award for Best Novel@en (http://dbpedia.org/resource/Hugo_Award_for_Best_Novel)) as the next candidate, and the original classification Item (http://www.wikidata.org/ontology#Item) is a class. Could it affect that?

_Copied from original issue: odalic/odalic-ui#133_

**Comment by brodecva** [comment]
@KataBoku  also reports, that even the candidates are somehow sometimes messed up.

@josef-janousek You told me on Skype, that the algorithm is unable to return more than one class as the chosen. This makes sense, unfortunately it effectively prohibits us from sending more that one chosen classification per column as a feedback. It also hard to do it in such way, that we would pick one of the chosen classification as the primary one, because there are no clear criteria how to choose one. Ah, I am kinda mad that I did not expect this.

Assigning to Tomas, I will explain the situation to him.

**Comment by tomas-knap** [comment]
S tím ale netuším, jak si poradit zatím, proto jsem přiřadil Tomášovi k vyjádření. V zásadě jde o to, že TableMiner+ sám nevrací více než jednu vybranou klasifikaci na sloupec, a tím pádem není jen tak možné mu nakázat feedbackem, aby jich vzal více.
Nechápu, jak jsem si to nemohl všimnout dříve.

**Comment by tomas-knap** [comment]
As discussed, proposed solution: Just please document in the wiki - in the https://grips.semantic-web.at/display/ADEQ/Odalic+Core subtree - that there is such a limitation of the algorithm.  
For now, we will go only for one classification per KB.

**Comment by brodecva** [comment]
@tomas-knap Closing. The documentation is dealt with in #222 .
