### ISSUE TITLE
Algorithm does not respect manually set column relation containing a resource added from a search

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#205]
Just add some entity from the search to the relations and the relations set in the feedback are not respected when re-run.

**Comment by tomas-knap** [comment]
@josef-janousek Is it clear what has to be done? If not, please ask. Thanks!

**Comment by brodecva** [comment]
Fixed as of https://github.com/odalic/sti/commit/e4097d0ac28f7d0ad61ef335dc01726cf92fa348 .
