### ISSUE TITLE
Add support for cell/all cells in  a column ambiguities in feedback by reducing this problem to empty chosen set in the cell disambiguation

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#213]
The ambiguities should have priority over disambiguations. So whenever you have a command to make cell ambiguous, it overrides any custom disambiguations attached to it.

**Comment by tomas-knap** [comment]
@brodecva Can you please explain a bit more what is the idea?

**Comment by brodecva** [comment]
It is a duplicate of #209.
