### ISSUE TITLE
Search does not suggest reasonable resource for classifications

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#215]
Was testing search component. Run books1.csv, go to details for the Book column and search for "Book". It suggests: 

![screen shot 2016-11-18 at 15 11 18](https://cloud.githubusercontent.com/assets/3014917/20432836/4fe6f93e-ada1-11e6-97e0-e5b3fbdaf84f.png)

If I am searching for a class (resource classifying the column), it should not find arbitrary URL (arbitrary resource), but resource which is actually instance of rdfs:Class or owl:Class. 

TODO for Honza: Add link to grips page which describes how is it implemented now
TODO for Tomas: provide better guidance how to improve that.

(Also if there is a precise match (e.g. for Book, there is http://schema.org/Book with rdfs:label Book), this should be first choice)

**Comment by brodecva** [comment]
It duplicates the #206, but as this issue has richer comments from @tomas-knap , I will close that one instead.

**Comment by JanVana** [comment]
@brodecva Please update the API.

**Comment by tomas-knap** [comment]
For @brodecva, as discuss on Friday, there should be extra param, which can be used by Honza to specify whether he is looking for ontological terms - classes, ontological terms - properties (searching relations), or other resources (disambiguation).

**Comment by brodecva** [comment]
> For @brodecva, as discuss on Friday, there should be extra param, which can be used by Honza to specify whether he is looking for ontological terms - classes, ontological terms - properties (searching relations), or other resources (disambiguation).

Done. I have also included potential range and domain restriction for the properties.

@tomas-knap Please look at https://github.com/odalic/odalic-ui/issues/170 to help us specify proposing of the properties, as it is a missing complementary feature.

@JanVana Hi, added, just follow the TODOs to implement searchClasses and searchProperties. I have renamed the original search(...)  method to searchResources(...), but otherwise it should remain the same (no filtering of classes is needed, as I can easily conjure a scenario when a class might actually be a valid cell disambiguation).

**Comment by brodecva** [comment]
@JanVana Concertning the restrictions (domain, range). to relations, you can ignore them for now. We will look into it with @tomas-knap further. Optionally, if you have spare time, you can try to give some priority to those results, that agree with the restriction, but this might be too time consuming. So on the first sight of trouble leave it be. Also, I may have said that the domain must be a sub-type of the source column class, but on the second look, it is the opposite - the domain should be at least as general as the source column class. The range should be a super-class of the target column class.

**Comment by JanVana** [comment]
@brodecva  I have implemented this feature, but i have ignored the domain and range for now. Those are properties of the searched properties. Are you saying, that a simple match is not sufficient?

**Comment by tomas-knap** [comment]
@JanVana What we wanted to have at least is not to show e.g. predicates when searching for resources classifying the column.
