### ISSUE TITLE
Add support for CSV meta-data provision

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#22]
https://grips.semantic-web.at/x/DIJ2B

Requirements 14, 63, 78

**Comment by tomas-knap** [comment]
@brodecva Please provide a bit more details, link to the story or at least to the req

**Comment by brodecva** [comment]
> Please provide a bit more details, link to the story or at least to the req

Done.

**Comment by brodecva** [comment]
The most essential things implemented as of https://github.com/odalic/sti/commit/e4097d0ac28f7d0ad61ef335dc01726cf92fa348 .
