### ISSUE TITLE
FileSystemException (acces by another process) during the algorithm run on a Lucene.*.doc file.

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#221]
Hi, @KataBoku cannot run a single task, because this exception is thrown every time. We have already checked that no other instance of the server is running, made clean checkout, changed Tomcat version, started from a clean cache...
Let us start resolving this bug (which seems to appear on @KataBoku 's PC) by asking @JanVana what might cause this, and whether a minor version upgrade (or even a not so minor) of Solr might resolve this?

**Comment by JanVana** [comment]
Could you please post more information about the bug? Like the exception details and the call stack?

**Comment by brodecva** [comment]
@JanVana I will forward you to @KataBoku , as it is her only, who is suffering from this problem. @KataBoku please, give @JanVana the log containing the call stack when the exception happens, for starters.

**Comment by brodecva** [comment]
@KataBoku reported that she was able to resolve the problem after all, but has no idea how, only that she tried to start from a clean slate.
