### ISSUE TITLE
Welcome page for odalic.war and intercept unmapped calls

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#226]
When accessing http://localhost:8080/odalic/, I got "page cannot be found". It would be good to display something, e.g. link to the documentation of the API so that:

1) it is clear the app was loaded successfully
2) there is something usefull there.

**Comment by tomas-knap** [comment]
Do 24.2. nebo nechat

**Comment by brodecva** [comment]
Welcome page added. The unmapped calls were already intercepted and return correctly HTTP 404 using the specified format in the REST specs.
Closed as of https://github.com/odalic/sti/commit/3a254318d26cdd002b9ce7af3528e399461dd071 .
