### ISSUE TITLE
Propose: Adjustments - Correctly specify class for entity (object of the real world), etc.

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#227]
Follow up of documentation activities: https://github.com/odalic/sti/issues/225

There are two issues to be corrected: 

1) In case entity (not class/predicate) is proposed, it should be automatically "instance of" of the  real class from the primary knowledge base which is used for classifying the column (and not the pre-configured root class).

If the class is not known (there is no classification from the primary knowledge base), such propose should fail with a message (it is necessary to first select/propose class for the column from the primary knowledge base).

2) Minor issue:  For class classificaiton, do not define the triple "X subClassOf Thing", as this is valid by default for all classes, there is no need to explicitly materialize that.

3) See: https://github.com/odalic/odalic-ui/issues/162, point 3). It should be possible to optionally add also further owl:equivalentClass triples expressing that the given class from primary knowledge base is equivalent to classes from other knowledge bases defined for the given column at the time when new enitty (object of the real world) is proposed.

**Comment by tomas-knap** [comment]
Related: https://github.com/odalic/sti/issues/208

**Comment by brodecva** [comment]
@tomas-knap This one was a bit hard to digest, I have split it into several individual issues ( https://github.com/odalic/odalic-ui/issues/178, #232 cover the 3., while https://github.com/odalic/odalic-ui/issues/178 covers the 1. and 2.

Closing this one as duplicate.

**Comment by tomas-knap** [comment]
@brodecva It is not clear to me which issue currently covers points 1) and 2)?
