### ISSUE TITLE
Export (extended table, RDF-turtle, json-ld) does not work

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#231]
To reproduce, use file: https://github.com/odalic/sti/files/622142/STMK_2012_LIVEBIRTHS-10lines.csv.zip

See also: https://github.com/odalic/sti/issues/175

Possible cause: Not all cell values disambiguated/classified. But it should be robust enough to work correctly 

It must at least report some reasonable issue - why it is not able to generate export!

TODO: Define how does it behave in case class/disamb is not complete

**Comment by josef-janousek** [comment]
Now it should be corrected.
When the value of classification/disambiguation is empty, then no triple is produced.

**Comment by brodecva** [comment]
An error found and a solution discussed with @josef-janousek , that appears on the reduced DBpedia dataset used.

**Comment by brodecva** [comment]
The fix seems to work, closing.
