### ISSUE TITLE
SparqlProxy not working correctly when textual values contain quotes

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#242]
3. Chyba při dotazování se na textové hodnoty obsahující uvozovky
- Jugend centers in Austria (#176)
    - v některých řádcích (např. řádek 6 či 17) jsou textové hodnoty, které obsahují uvozovky (jde o název Jugend centra)
To způsobilo chybu v metodě queryEntityCandidates ve SPARQLProxy. Problematické řádky by se opět musely ručně odstranit, což jsem nyní nedělal, takže soubor neprošel.
Rovněž jsem musel odstranit uvozovky v souboru Abstammung 2015 (enumeration of people) (#183), které způsobily tutéž chybu. Ale ty byly jen formátovací.

Currently, due to such values, the execution for the whole file fails with the following exception: 
![jugendzentren-error](https://cloud.githubusercontent.com/assets/17772934/21161774/531ad0d8-c18a-11e6-9ccf-2bf03b0cde27.png)

Solution: It must not fail, it must either process also such values or ignore such single label (it is not disambiguated e.g.)

**Comment by tomas-knap** [comment]
@JanVana This seems to be rather pressing, please solve that asap (till Thursday for sure, please, so that we 1) do not have such error in the release 2) we can continue with the testing on our testing data - this blocks e.g. https://grips.semantic-web.at/display/ADEQ/Jugend+centers+in+Austria and https://grips.semantic-web.at/pages/viewpage.action?pageId=76224229

**Comment by tomas-knap** [comment]
@JanVana Try row 17 of the Jugend centers in Austria file to retest

**Comment by brodecva** [comment]
@JanVana Any progress? Still waiting for your report.

**Comment by JanVana** [comment]
I have changed how strings are handled in full-text search. This issue should be resolved in the KBProxy_Priority_Fixes branch.

**Comment by JanVana** [comment]
Created task #311 as a suggested improvement.

**Comment by brodecva** [comment]
> Created task #311 as a suggested improvement.

Thank you, I'll make it so.

Anyway the quotes handling seems to be alright when i re-tested the reported file. Good job!

**Comment by brodecva** [comment]
Waiting for the complete pull request to pass.

**Comment by brodecva** [comment]
Closed by #310 .
