### ISSUE TITLE
Special german characters not properly supported in the testing files

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#243]
As was tested in #174-#183, 
Speciální znaky (ať už německé nebo jiné) nebyly správně zobrazeny. Vstupní soubory jsem nijak neměnil co se týká kódování, takže buď by se muselo zkusit kódování ručně změnit, nebo podporovat více kódování.

Current situation: Not correctly processed
Solution: Possibility to manually define encoding during definition of the task configuration, so that it is correctly processed

**Comment by brodecva** [comment]
@josef-janousek Hi, look into that again after your are able to set the appropriate encoding manually.

**Comment by josef-janousek** [comment]
Yes, after resolving issues #157 ( #245 ) and #270 these characters are displayed correctly when the user sets the appropriate encoding (manually).
