### ISSUE TITLE
Add basic server support for file metadata

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#245]
Records separator is enough for now.

**Comment by brodecva** [comment]
Needed as the lack of this feature is holding as back in testing of the provided sets.

**Comment by tomas-knap** [comment]
Fully agree, needed for the release at the end of December. At least possibility to manually define encodings, delimiters.

**Comment by tomas-knap** [comment]
See also: https://github.com/odalic/sti/issues/157 ( @brodecva align?)

**Comment by brodecva** [comment]
Done at https://github.com/odalic/sti/commit/5bfd0918431887bc86c084a8314e79483f10a88c .
