### ISSUE TITLE
KbProxy - NullPointerException during testing whether the class is valid

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#248]
Processing of the Top Locations file, see: https://grips.semantic-web.at/display/ADEQ/Top+Locations+in+Wien, was not correct due to some issue in KbProxy:

![locations-error](https://cloud.githubusercontent.com/assets/3014917/21176352/9acd05ca-c1e6-11e6-960e-0a0d1d5eda5e.png)

It seems that some NullPointerException was thrown from KbProxy. Solution: In this cases, warn/error should be logged and there is no disambiguation/classification for certain column/cell but it should not cause that the whole process fails.

**Comment by brodecva** [comment]
Hi, @josef-janousek, I have merge the #279 that should resolve this issue. But I need to verify it on the original file. Please do so, and also provide us with a cleaned up file without those pesky superfluous semi-colons, or point me to it. I was not sure if I could use the file in GIRPs to actually do the test. Thanks!

**Comment by josef-janousek** [comment]
@brodecva When you set the quote character to double-quotes ( " ), then no more problem with semicolons will appear and you can use the original file from Austrian portal.
When I tested it with restriction to 2 lines, the task was processed successfully (after about 10 minutes). But when I tested it with 20 lines, this error appeared again.

**Comment by josef-janousek** [comment]
@JanVana Consider solving it together with #166 to discover what concrete row / cell caused this problem.

**Comment by JanVana** [comment]
A have tested the mentioned file and it should be resolved.

**Comment by brodecva** [comment]
> A have tested the mentioned file and it should be resolved.

It is resolved in #310 ? or somewhere else?

**Comment by brodecva** [comment]
@JanVana I will test it only after the #310 gets accepted. Until then is too much hassle to switch between to config sets. Hope, you and @tomas-knap won't mind.

**Comment by brodecva** [comment]
I had tried but after several hours it failed on 404. But this issue is covered in other issue. No NullPointerException occured.
