### ISSUE TITLE
No classes assigned after cache emptied

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#249]
I have emptied a cache and when i run Books.csv or any other file. the headers are not classified. What happened? I did not notice it before, because I did not test it without cache.

**Comment by JanVana** [comment]
I will try to fix this today.

**Comment by tomas-knap** [comment]
@JanVana Probably the problem was introduced in the latest changes (after 9.12.), because I am using the version from 9.12. and I cleared the cache couple of times and it worked.

**Comment by brodecva** [comment]
@tomas-knap Yes, it emrged somewhere between ebfdcf2878214cbd9f86bec2b0c2715ae8493846 and 0b6a592a98aacba3059068dc9ca4104226360c88 .

**Comment by brodecva** [comment]
@JanVana will fix during the SPARQL refactorization. Hopefully ;-) .

**Comment by brodecva** [comment]
Hi, @JanVana , please report. Considering this issue essentially breaks the application, we are waiting for the solution or even analysis for too long.
If there is no progress in this matter, I would be forced to revert a several of the accepted commits, which I am definitely not looking forward to, in order to provide @tomas-knap  a working server instance for tomorrow meeting.

**Comment by JanVana** [comment]
Hi @brodecva, this issue is fixed in the feature/sparqlProxyRefactoring branch.

**Comment by JanVana** [comment]
The fix is part of the #255 pull request and ready to be merged.
