### ISSUE TITLE
Integrate chosen KB concept browsing and selection component

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#25]
Try to find existing implementation first.
Should display the context in the KB (using its ontology).
Also should be usable to pick a concept.

The implementation can be mocked in the 1st iteration.

Requirements 19. 52.

**Comment by istvan-satmari** [comment]
- Not understood. Specify in detail, what should be done. 
- To what extent does the feedback matter for the first iteration? Is it just a mean to provide a result for a user, or do we really expect a mechanism for reexecuting a task with a  provided user input constraints (= feedback)? <- THIS IS IMPORTANT QUESTION.

**Comment by brodecva** [comment]
As illustrated in the mockup at https://grips.semantic-web.at/display/ADEQ/Scenario+4b+Customizing+classification+class+-+selecting+different+non-suggested+primary+class+for+the+column+classification , this component visualizes the selected concept in the knowledge base and allows to change the used concept in the context it is opened from (when classifying column, selecting the relation predicate,...) or pick one when no concept was selected before.

It is initialized with the concept it is called upon (the used concept should imply its parental KB) and show is in its closest neighbourhood (according to the associated ontology). When opened when no concept has been selected yet, it might be necessary to choose one of the available KBs (this might be skipped for the 1st iteration, as we might be working with only one at the moment) and then it will be probably display the root element (usually something general, like a thing or something) according to the associated ontology.

The feedback just won't be implemented in the 1st iteration and I do not expect that we will be able to correctly implement multiple passes of the same task too in time.

For this issue and iteration it means that it is fine if this component displays only some dummy data and any actions made don't have any effect.

On the other hand, I guess there might be some already existing reusable components doing this, that it might in the end prove to be simpler´and faster (and much more impressive) to  actually use one and attach it to our used KB (DBpedia for now) , than try to provide some mocked, not mentioning home-cooked implementation. Even in this case the chosen action might not have any effect (the concept won't change or filled), but at least the browsing will be working.

**Comment by brodecva** [comment]
Also notice that #63 covers providing the interface to the KB on the server, so communicate with the assignee of this issue when the time comes.

**Comment by brodecva** [comment]
This issue was moved to odalic/odalic-ui#26
