### ISSUE TITLE
Secure a working Bing API access after the 90 days trial

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#251]

**Comment by brodecva** [comment]
The trial started on 2016-12-14. I did not study the terms in much detail, but AFAIK we have to pay after the trial ends or if we go beyond the limit of the trial version.

**Comment by brodecva** [comment]
@tomas-knap We should fix this before delivery, as the trial period ends within two weeks.

**Comment by tomas-knap** [comment]
I generated two more keys today, see: https://grips.semantic-web.at/display/ADEQ/Testing+environment

**Comment by tomas-knap** [comment]
@brodecva Please test
