### ISSUE TITLE
Document Search service

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#253]
It has to be documented how the services being used to search for classes, entities from the UI work (I mean the services which allow users to search for alternative resource not suggested by Odalic).

Please document that under: https://grips.semantic-web.at/display/ADEQ/KB+Search
(I already started a bit, you may create also separate sub page for each different parameter (class/predicate/data) to that service if usefull)

**Comment by JanVana** [comment]
I have made some changes to the configuration and configuration loading to increase consistency. The relevant pull request is #383.

**Comment by brodecva** [comment]
Closed by #383 .
