### ISSUE TITLE
Profile the application - KB search

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#257]
The goal is to use some profiling tool to find out where most of the time is spent during running of Odalic for the first time (so that we can figure out and maybe know what to tune in order to speed up the first execution). 

So result of this task should be ideally a link to wiki page, where the results of the performance testing is provided. Result should be some discussion, probably supplemented with a graph from the profiling tool. 

This should be probably provided by @JanVana as the problem will be probably in the KB search, which is anyway part of his thesis ;-)

Marking as Milestone 4 - could be done during Christmas?

**Comment by tomas-knap** [comment]
We should at least have idea what consumes most of the time

**Comment by tomas-knap** [comment]
@JanVana We should have at least idea what is slowest

**Comment by tomas-knap** [comment]
Just basic idea

**Comment by brodecva** [comment]
@JanVana Hi, please do not forget to look into this!!!

**Comment by JanVana** [comment]
I have started adding profiling results here: https://drive.google.com/open?id=0B-BaaOfP11_oTFNSLThUSzI0Wkk

**Comment by JanVana** [comment]
I have created a page for profiling in grips: https://grips.semantic-web.at/display/ADEQ/Profiling
