### ISSUE TITLE
NUTS1 classified too generally

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#259]
See https://grips.semantic-web.at/display/ADEQ/Number+of+new+babies+by+the+cities%2C+districts . Although all cells were disambiguated, no class was found for. Try to answer why and propose a fix.

**Comment by tomas-knap** [comment]
With the full dbpedia, this does not happen.

**Comment by brodecva** [comment]
> With the full dbpedia, this does not happen.

Really? It does according to https://grips.semantic-web.at/display/ADEQ/Number+of+new+babies+by+the+cities%2C+districts .

**Comment by josef-janousek** [comment]
In current version NUTS1 class is already assigned:
![stmk_2012_livebirths_nuts](https://cloud.githubusercontent.com/assets/17772934/21610889/c9adda38-d1ca-11e6-8e45-8aae30d77c55.png)

**Comment by brodecva** [comment]
@josef-janousek Still too generally. It is iteresting though, that the German DBpedia is more specific than the English one.

**Comment by tomas-knap** [comment]
AD KB changed, now invalid
