### ISSUE TITLE
NUTS2 classified too generally

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#260]
See https://grips.semantic-web.at/display/ADEQ/Number+of+new+babies+by+the+cities%2C+districts . Although all the cells in the columns are disambiguated, the chosen class is too general. Try to find out why? (NUTS2 specific class missing, no ontology links,...)

**Comment by brodecva** [comment]
Also the LAU_NAME column in the same set.

**Comment by tomas-knap** [comment]
Searching in AD KB changed quite a bit, now invalid
