### ISSUE TITLE
Add support for custom types

### ISSUE THREAD

**Issue by JanVana** [odalic/sti#261]
As of now, SPARQLProxy uses hardcoded rdf:type, change this to user defined type from enums.

**Comment by tomas-knap** [comment]
Postponed as rdf:type is used in all cases which came to my mind.

**Comment by tomas-knap** [comment]
When having just skos hierarchy, then also other predicates may play the role of rdf:type, e.g. skos:broader. Evaluate and decide if customization needed.

**Comment by tomas-knap** [comment]
When checking config files, I can see that I can define as well: 

kb.predicate.type=http://www.w3.org/2004/02/skos/core#broader http://www.w3.org/1999/02/22-rdf-syntax-ns#type

To express that the "instanceOf" predicate could be the standard rdf:type, but also something else. So there is already support for that. 

Please quickly (<1h) double-check that such custom config is taken into account where it should be taken and close if ok

**Comment by JanVana** [comment]
kb.predicate.type is only used when the KBproxy selects types from all attributes of a resource. It is not used in SPARQL queries directly.

**Comment by JanVana** [comment]
The main technical difficulty is in the fact, that the there are queries, where we restrict results to only a certain set of types. This is implemented in SPARQL as union:

```
{?subject rdf:type <Type1>} UNION {?subject rdf:type <Type2>}
```

Adding the ability to configure multiple type predicates would lead nested UNIONS:

```
{{?subject rdf:type <Type1>} UNION {?subject rdf:type <Type2>}} UNION {{?subject skos:broader <Type1>} UNION {?subject skos:broader <Type2>}}
```

All SPARQL queries will have to be changed into this nested UNION format, which will take a day or two.

**Comment by tomas-knap** [comment]
Then please leave it as it is for now

**Comment by tomas-knap** [comment]
Because we would also probably decrease the performance of query exec and in many cases rdf:type is the obvious choice.

**Comment by tomas-knap** [comment]
TODO decide whether we should adjust

**Comment by tomas-knap** [comment]
Won't fix for now
