### ISSUE TITLE
Gather processing warnings and add them to the processing result

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#262]
The Result class constructor provides an option to add a list of warnings that will be passed to the user. The warnings are events or even mild errors that occurred during the processing, but did not halt the processing, yet may be of concern to the user.
Your task is to find all the places where such events occur and enable us to gather them (the original TAnnotation will be probably extended or alternative mean of warnings detecting and aggregation might be found: for example log analysis?) and ultimately pass them to the Result constructor whenever it is called.

**Comment by tomas-knap** [comment]
Note: How do we show these warning in the UI? There should be yet another icon apart from "Everything ok" and "error", e.g. something as "OK, with warnings" ?.

**Comment by brodecva** [comment]
@tomas-knap Apparently in the current state any exception halt the entire process, so this is not relevant until finer approach is established, e.g. by #166 .

**Comment by brodecva** [comment]
> Note: How do we show these warning in the UI? There should be yet another icon apart from "Everything ok" and "error", e.g. something as "OK, with warnings" ?.

@tomas-knap Yes, such state is already supported since the end of the 3rd iteration.
