### ISSUE TITLE
SparqlProxy - queryForLabel not defined reasonably for generic SparqlProxy

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#273]
Currently, @JanVana just copied queryForLabel from dbpediaProxy to generic sparqlProxy - but this is not correct, in most cases there is no sense to look e.g. for some yago resource etc. - so it is necessary to provide more suitable generic version of queryForLabel, which is valid for a generic SPARQL Endpoint

See: 
https://github.com/odalic/sti/blob/develop/sti-kbproxy/src/main/java/uk/ac/shef/dcs/kbproxy/sparql/SPARQLProxy.java#L228-L276

**Comment by JanVana** [comment]
I have changed the query for label method. The yago check is now in the DBpediaProxy. Everything else seems to be general enough to be in the SPARQLProxy.

I thought that the Yago is a general ontology used in many knowledge bases, but what I didn't realize is, that the code fixes only DPpedia links pointing to Yago concepts.

**Comment by JanVana** [comment]
Should be fixed in the #333 pull request
