### ISSUE TITLE
Either support a file without any rows (apart from the header) or include checks for at least one row

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#280]
The algorithm fails when there are no regular rows. Either fix the algorithm or prevent the cause.

**Comment by brodecva** [comment]
It might be best to get approval from @tomas-knap first, when you decide to allow only 1+ rows files.

**Comment by tomas-knap** [comment]
I would suggest to just report to the user that there is not data in the file. But for sure, we should not fail with some strange exception.
