### ISSUE TITLE
Test Odalic against Testing data

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#288]
See: https://grips.semantic-web.at/display/ADEQ/Testing+Data

This is a task which should be done periodically.

**Comment by tomas-knap** [comment]
@josef-janousek Please test everything again in the week 23.-27.1.

**Comment by tomas-knap** [comment]
@josef-janousek Please let me know by Friday what is the status, thanks!

**Comment by tomas-knap** [comment]
Please test also for the ADEQUATe KB!

**Comment by josef-janousek** [comment]
Testing completed, all tasks finished successfully, testing page in grips https://grips.semantic-web.at/display/ADEQ/Testing+Data updated - DB file with results and text file with durations of tasks can be downloaded there.
