### ISSUE TITLE
Create UnifiedViews DPU for Odalic

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#289]

**Comment by tomas-knap** [comment]
For that, we need to have the configuration export option, so that we can export config and import it in UV. Based on that, UV can then register the task at certain REST API and run the task. If we have export, it should be matter of day to prepare that

**Comment by tomas-knap** [comment]
Depends on #37

**Comment by tomas-knap** [comment]
Help @brodecva to realize that in the week from 6. (probably 9.2/10.2.?)
