### ISSUE TITLE
Allow forbidding disambiguation of all cells for arbitrary column

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#29]
Mind the edge cases (what if user picks the subject column, what if there are no columns left,...).

**Comment by brodecva** [comment]
Story at https://grips.semantic-web.at/x/GBdsB .

**Comment by tomas-knap** [comment]
So what is the difference from just ignoring the column? The difference is that the column is classified, but no disambiguations are introduced?

**Comment by brodecva** [comment]
> So what is the difference from just ignoring the column? The difference is that the column is classified, but no disambiguations are introduced?

Yes, this is the difference.

**Comment by brodecva** [comment]
Links to #223.
