### ISSUE TITLE
Search for a long or empty string returns 500

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#292]

**Comment by JanVana** [comment]
I have changed the implementation of the user search to never return exceptions. In case of an exception, it is logged and an empty result is returned.

I do not think it is feasible to do try and parse the HTTP result for more information on the error. It is most likely to be one of two cases:
1) The searched string breaks some rule for full text search (like length, or number of letters in words).
2) The KB is not working.

In both cases it seems best to return only empty result.

**Comment by JanVana** [comment]
It should be implemented in the #334 pull request.
