### ISSUE TITLE
The class of a proposed cell resource is not stored

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#296]

**Comment by brodecva** [comment]
@JanVana Any progress? Still waiting for your report.

**Comment by JanVana** [comment]
I have tested this and the class is saved in the KB.

**Comment by JanVana** [comment]
Created the improvement #312, that might be connected to this issue.

**Comment by tomas-knap** [comment]
I will try to also test when connecting to ADEQUATE KB, connected with #312

**Comment by brodecva** [comment]
@JanVana @josef-janousek @tomas-knap Actually it is probably be caused by #308 .  So I see no reason to leave this one open.

**Comment by tomas-knap** [comment]
Does not work, testing with current develop (12.1.) on booksv1 on top of jan's KB. 




Steps: 
1) Propose a new resource for Steve Ericsonn, you can see there is class mentioned. 
2) There is the new resource, but there is no triple saying that it is instance of class X

![screen shot 2017-01-12 at 16 41 34](https://cloud.githubusercontent.com/assets/3014917/21896494/e2effdd2-d8e6-11e6-8962-a8ad1b4dcd2a.png)

![screen shot 2017-01-12 at 16 43 14](https://cloud.githubusercontent.com/assets/3014917/21896489/dd392562-d8e6-11e6-8aa6-ea8632bdc843.png)

**Comment by JanVana** [comment]
@tomas-knap  I do not understand the problem. The rdf:type seems to be assigned correctly, is there some other predicate used as "instance of"? Would it be possible to write a short example of what triples should be saved to the KB?

**Comment by tomas-knap** [comment]
Sorry, I was testing quite a lot tomorrow and overlooked that it is actually there ;-) Sorry for confusion.
