### ISSUE TITLE
Jena ignores limits in subselects

### ISSUE THREAD

**Issue by JanVana** [odalic/sti#313]
The SelectBuilder used from Jena does not work well. It sometimes create queries with unnecessary subselect. These queries then ignore any limits set on the number of results.

I would like to rethink the current solution.

**Comment by brodecva** [comment]
@JanVana Yeah, finally noticed it. It ignores the limit when searching for a cell resource!

**Comment by tomas-knap** [comment]
So this was solved by #471 ?
