### ISSUE TITLE
Caching of search results - I would suggest to disable

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#316]
I think it is not a good idea to cache the results, because right now if the KB is adjusted, e.g. new concepts are proposed, user may not be able to find such new resources, because of older results in the cache for queries asked before. So if he asks "Orte" and there is no such resource and then propose "Orte" as a new resource, he is not able to find it via search anymore. 

So I would suggest to comment the line: https://github.com/odalic/sti/blob/develop/sti-kbproxy/src/main/java/uk/ac/shef/dcs/kbproxy/sparql/SPARQLProxy.java#L418 and comment the storing/loading search results from cache. I would start with simply running the query always against the target endpoint. If the time shows cache is needed, we should go for a bit more smart cache/

**Comment by brodecva** [comment]
> So if he asks "Orte" and there is no such resource and then propose "Orte" as a new resource, he is not able to find it via search anymore.

@JanVana @tomas-knap Why does the cache even remembers negative results? It should be definitely the case, that when I add a new resource, the cache should take that into account.

> If the time shows cache is needed, we should go for a bit more smart cache/

@tomas-knap Well, there is no possibility of a presentation in acceptable time unless all the results are pre-cached. I suspect the caches are not even large enough to keep the entities needed for even one run, and if you decide to run file, then another, and then the first one, you almost start anew, if the files are larger than 4 - 5 lines! I would almost say that we should make the caches as large and smart as possible...

**Comment by tomas-knap** [comment]
Sorry for confusion, what I meant here is to disable caching of results when user is manually searching KB via "Search" box.

**Comment by JanVana** [comment]
The cache is disabled in the #316 pull request.
