### ISSUE TITLE
Preliminary classification does not work for manually suggested disambiguations where the type attribute is missing

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#318]
Steps to reproduce: 

Run a file with e.g. 3 data rows (Book e.g.). Select the column which was classified and values disambiguated to at least to two different entities in total. Then adjust all disambiguations to something else for all cell values in that column (e.g. to some disambiguations in a different column, again having at least two different disambiguations in that column). Try re-executed. 

What I would expect is that the class is adjusted based on the adjusted disambiguations. But there is an issue. If the entity is manually disambiguated, the standard "findEntityCandidates" method at kbproxy is not called (see below), but only the URI and label is obtained for that manually added disambiguation. **As a result, the preliminary classification does not work correctly, because the preliminary disambiguated entities do not have "type" attributes (see below, it is null), so there are not types which may vote for classification**. As a result, the algorithm probably randomly, or based on the web search, selects the classification. 

![screen shot 2017-01-12 at 12 00 37](https://cloud.githubusercontent.com/assets/3014917/21887890/3096fb82-d8c2-11e6-9181-0667d14f85bf.png)

Original class with all disambiguations changed:

![screen shot 2017-01-12 at 11 43 59](https://cloud.githubusercontent.com/assets/3014917/21888207/7d7298f2-d8c3-11e6-9809-57ad211105cd.png)

Then re-rerun. As a result, the algorithm probably randomly, or based on the web search, selects the classification. In the case below, it even selected the predicate for classification:

![screen shot 2017-01-12 at 11 44 51](https://cloud.githubusercontent.com/assets/3014917/21888155/3c10840a-d8c3-11e6-9e36-176e7af814a8.png)

**Comment by josef-janousek** [comment]
@JanVana I think that the support from KBProxy is needed. My opinion:

> myslím, že bych k tomu potřeboval podporu od KBProxy - nejlépe asi tak, že podobně, jako má metodu findEntityCandidates(String content) , která hledá entity podle labelu a při zadaném feedbacku už její volání vynecháváme, by měla ještě podobnou metodu, která by hledala přímo podle adresy resourcu, případně adresy + labelu (což bychom ji právě předali z feedbacku) a očekávalo by se, že najde jen jednu entitu, ale vrátí ji kompletní včetně nastavených atributů (a tím by zároveň i ověřila existenci entity z feedbacku v duchu úkolu #302)

Would it be possible to do it this way?

**Comment by JanVana** [comment]
It is no problem to a method like that.

**Comment by tomas-knap** [comment]
@JanVana please prepare such method (discuss with @josef-janousek if needed) and then assign to @josef-janousek  to finalize

**Comment by tomas-knap** [comment]
Test is needed

**Comment by josef-janousek** [comment]
Loading entities from Feedback (disamb.) adjusted - using the method for loading directly from KBProxy.
@JanVana @brodecva It seems that loading of attributes of entites works well, so pull request can be created.
