### ISSUE TITLE
Adjustments to the exported data - values of data properties - should contain dataTypes as well

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#325]
The exported data should contain also datatypes for predicates (relations) e.g. between the subject column and some literal (number).  Currently, if the value of the predicate is literal, there is no dataType for that literal. 

Note: It should work in a way that if there is range for certain predicate, which is different from "xsd:String", then such datatype (range) should be attached to the produced literal. 

Note: On the other hand, if the value of the predicate is String, there should be language tag (based on the language of the KB - in the config) 

For that, the export service requires a simple service from KBProxy , which would give him some triples about the requested predicate (or just "range" of that predicate).

**Comment by brodecva** [comment]
@josef-janousek Hi, could you look into it?
@josef-janousek @tomas-knap Concerning the proposed service: I think that the relation type is is something that should be filled during algorithm run and not queried later.

**Comment by tomas-knap** [comment]
Ok, yes, that is also possible - to directly return by the algorithm. And it is not that much data, so lets do that in that way - to directly enrich what is returned by the algorithm (with e.g. domains/ranges)

**Comment by tomas-knap** [comment]
For literal objects - datatype properties

**Comment by JanVana** [comment]
I have added the two methods into the KBProxy (getPropertyDomains and getPropertyRanges). My commits are in the branch 325.

**Comment by brodecva** [comment]
Closed by #376 .
