### ISSUE TITLE
Not able to get list of Knowledge bases on remote server (not localhost)

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#326]
I deployed Odalic again od ADEQUATe testing server, so that Ziqi and others can test, but the list of KBs is not loaded properly when new task is being created. I adjusted in UI the odalic root to:

 get odalicroot() {
                return 'http://adequate-project-odalic-ui.semantic-web.at/odalic/';
            }

![screen shot 2017-01-18 at 16 18 15](https://cloud.githubusercontent.com/assets/3014917/22069763/e40e8b9a-dd99-11e6-8a0d-0108e6cb2744.png)

You may test that on: 
http://adequate-project-odalic-ui.semantic-web.at/odalic-ui/

Nevertheless, certain API calls work, e.g.: 
http://adequate-project-odalic-ui.semantic-web.at/odalic/files

But http://adequate-project-odalic-ui.semantic-web.at/odalic/bases?modifiable=true, return 500 (but there should be two modifiable KB defined)

Maybe the URL (localhost) is hard-coded somewhere?
Using commit: e4097d0ac28f7d0ad61ef335dc01726cf92fa348 (almost latest, still with lazy loading of KBs)

**Comment by tomas-knap** [comment]
Please look on that asap, so that I can send that to Ziqi as soon as possible.

**Comment by brodecva** [comment]
Hi, @tomas-knap , I have tried it at your running instance. The API works and this is what the API call returns (notice the bold text). It seems that the paths to KB definitons are misconfigured. Check that please first.

> {"status":500,"type":"MESSAGE","payload":{"additionalResources":[],"text":"Failed initializing KBProxies.","debugContent":"uk.ac.shef.dcs.sti.STIException: Failed initializing KBProxies.\n\tat cz.cuni.mff.xrg.odalic.tasks.executions.DefaultKnowledgeBaseProxyFactory.initKBProxies(DefaultKnowledgeBaseProxyFactory.java:93)\n\tat cz.cuni.mff.xrg.odalic.tasks.executions.DefaultKnowledgeBaseProxyFactory.initComponents(DefaultKnowledgeBaseProxyFactory.java:69)\n\tat cz.cuni.mff.xrg.odalic.tasks.executions.DefaultKnowledgeBaseProxyFactory.getKBProxies(DefaultKnowledgeBaseProxyFactory.java:52)\n\tat cz.cuni.mff.xrg.odalic.bases.DefaultBasesService.getProxiesStream(DefaultBasesService.java:55)\n\tat cz.cuni.mff.xrg.odalic.bases.DefaultBasesService.getBases(DefaultBasesService.java:40)\n\tat cz.cuni.mff.xrg.odalic.api.rest.resources.BasesResource.getBases(BasesResource.java:51)\n\tat sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)\n\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)\n\tat org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:315)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:297)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:267)\n\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)\n\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)\n\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)\n\tat org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)\n\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)\n\tat org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)\n\tat org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)\n\tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)\n\tat org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: uk.ac.shef.dcs.kbproxy.KBProxyException: java.lang.reflect.InvocationTargetException\n\tat uk.ac.shef.dcs.kbproxy.KBProxyFactory.createInstances(KBProxyFactory.java:61)\n\tat cz.cuni.mff.xrg.odalic.tasks.executions.DefaultKnowledgeBaseProxyFactory.initKBProxies(DefaultKnowledgeBaseProxyFactory.java:87)\n\t... 50 more\nCaused by: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.GeneratedConstructorAccessor115.newInstance(Unknown Source)\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\tat uk.ac.shef.dcs.kbproxy.KBProxyFactory.createInstances(KBProxyFactory.java:52)\n\t... 51 more\nCaused by: org.apache.jena.shared.WrappedIOException: **java.io.FileNotFoundException: /opt/odalic/resources/resources/dbpedia_ontology_2014.owl (No such file or directory)**\n\tat org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:291)\n\tat org.apache.jena.ontology.impl.OntModelImpl.readDelegate(OntModelImpl.java:3092)\n\tat org.apache.jena.ontology.impl.OntModelImpl.read(OntModelImpl.java:2190)\n\tat org.apache.jena.ontology.impl.OntModelImpl.read(OntModelImpl.java:2106)\n\tat uk.ac.shef.dcs.kbproxy.sparql.DBpediaProxy.loadModel(DBpediaProxy.java:76)\n\tat uk.ac.shef.dcs.kbproxy.sparql.DBpediaProxy.<init>(DBpediaProxy.java:40)\n\t... 55 more\nCaused by: **java.io.FileNotFoundException: /opt/odalic/resources/resources/dbpedia_ontology_2014.owl (No such file or directory)**\n\tat java.io.FileInputStream.open0(Native Method)\n\tat java.io.FileInputStream.open(FileInputStream.java:195)\n\tat java.io.FileInputStream.<init>(FileInputStream.java:138)\n\tat java.io.FileInputStream.<init>(FileInputStream.java:93)\n\tat sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)\n\tat sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)\n\tat java.net.URL.openStream(URL.java:1045)\n\tat org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:288)\n\t... 60 more\n"},"stamp":null}

**Comment by tomas-knap** [comment]
Corrected, working, thanks
