### ISSUE TITLE
Add task configuration option limit to limit input size to certain number of rows

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#33]
Requirement 25.

**Comment by tomas-knap** [comment]
https://grips.semantic-web.at/display/ADEQ/Story%3A+Preview+exported+RDF+data

Nice to have

**Comment by brodecva** [comment]
Turn it into two tasks, just restrict the read lines.

**Comment by brodecva** [comment]
Agreed that this will make the testing easier. I will try to add it tomorrow.

**Comment by brodecva** [comment]
Done in https://github.com/odalic/sti/commit/658bb57cbe96d0b31cbf13d0d3b8f3951555a8e7 .
