### ISSUE TITLE
Fix the algorithm to find data properties

### ISSUE THREAD

**Issue by JanVana** [odalic/sti#349]
I think that the algorithm searches only by label. I will check if it can find data properties, that have no labels.

**Comment by tomas-knap** [comment]
Check how that works and document to wiki

**Comment by JanVana** [comment]
It seems to me, that the only part of the core algorithm, where cell values are compared to subject column attributes, is in the JIAdaptedAttributeMatcher. And since we use the TMP algorithm, we do not use this feature.

**Comment by tomas-knap** [comment]
So it seems that the algorithm does not suggest data properties at al?

**Comment by tomas-knap** [comment]
From Ziqi: it should work for both entity-entity column and entity-data column. In the first case, we treat it as a relation. in the second case, it is a property.

**Comment by tomas-knap** [comment]
Try it on this example: 

CSV: 
City;Population
Prague;1259079
Paris;2240621

The numbers are exactly the same number as are in your dbpedia KB for total population of these two cities. Run it against your dbpedia and debug the algorithm (odalic core) to see why the predicate (http://dbpedia.org/ontology/populationTotal) was not suggested (I tried, not selected, but did not have time to debug the code)

**Comment by tomas-knap** [comment]
Estimation: 1-2h

**Comment by tomas-knap** [comment]
Till 3.3

**Comment by JanVana** [comment]
The uk.ac.shef.dcs.sti.core.algorithm.tmp.LiteralColumnTagger should provide this functionality, but I have yet to see any dataproperty in the result.

**Comment by tomas-knap** [comment]
TODO: Try to experiment a bit more with that to have better answer:
1) working
2) not working, there is bug, fixed
3) not working, too complex to fix for now

**Comment by brodecva** [comment]
@josef-janousek will write to Ziqi.
