### ISSUE TITLE
Disallow certain characters as identifiers

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#355]
This could avoid various issues:
- if I create task with the same name, it overwrites previous task - this is major issue as this may happen quite easily (task "test")
- special chars in the task name, which causes troubles now, e.g. "test/result"
- problem that name cannot be changes
- issue with import - name may already be there, ... this could bring issues when moving task configurations between Odalic instances
- Also it is not that intuitive now that "task name" is also task id -> can be solved by renaming to task id 

@brodecva Please consider use of UUID (and name just as an attribute), please estimate time effort. Then we can discuss further. 

As a minimal solution, if not going for UUIDs, we should at least check for certain chars ("/"), it would be also good  not tp allow the task with the same name.

**Comment by brodecva** [comment]
We have opted for more meticulous input checking instead. The only thing needed is to add the checking of used chars at the server. Switching to me.

**Comment by brodecva** [comment]
Closed as of https://github.com/odalic/sti/commit/7878d0c7a2f20e738c55e636333a45aaac43d48a .
