### ISSUE TITLE
If you change task description, you have to re-run the task

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#356]
Adjust in a way that it is not needed to re-run for certain attributes - e.g. description.

**Comment by brodecva** [comment]
@tomas-knap I have fixed this. But it seems there is a bug in the UI, that whenever the task configuration is chagned, an empty feedback is sent to server instead of the current one. I will close this one and create bug issue for the UI that will deal with this.

**Comment by brodecva** [comment]
Closed as of https://github.com/odalic/sti/commit/7e0574799b4c9280b2dccd2a45062e2506720deb .
