### ISSUE TITLE
Prefixes for domain/range correctly used during proposing relations

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#357]
When proposing new resource (relation), one may use prefix when defining domains/ranges. Please ensure that then the prefixes are correctly interpreted when such resource is being created in the KBs. 

Quite simple solution is to basically include all the prefixes to the query which creates new resources, so that they are available to the query.

**Comment by brodecva** [comment]
@JanVana There exists the so called PrefixMappingService, which could be easily extended with a method providing the list of defined indices.

**Comment by JanVana** [comment]
Implemented in pull request #374. All SPARQL queries should now have correctly set prefixes.

**Comment by brodecva** [comment]
Closed by #374 .
