### ISSUE TITLE
Propose resource, than cannot be find via manual Search

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#359]
We come to that during discussion on Friday. Cause by fulltext matching, which requires strings to be indexed, which takes some time.

As we discussed, can be solved by using exact match first. 

Note - this may restrict quite a lot results of search in certain cases. If I write a string (e.g. prefix for some word) which accidentally matches something else - 
**maybe the best would be to run exact match and then fulltext match and combine results!**

**Comment by JanVana** [comment]
Implemented in pull request #374.

**Comment by tomas-knap** [comment]
Please do not forget to document this change

**Comment by brodecva** [comment]
Closed by #374 .
