### ISSUE TITLE
Propose for data cube - dimensions and measures does not work?

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#365]
Please check that propose works correctly for statistical data - proposing dimensions or measures

For me I got: 

![screen shot 2017-02-08 at 11 17 26](https://cloud.githubusercontent.com/assets/3014917/22733711/3cee944e-edf3-11e6-8b7b-ca6e887eb7dd.png)

But I used backend from 1.2.

**Comment by brodecva** [comment]
@tomas-knap Works for me as of the latest UI and develop version, well unless the cases when the issue #364 manifests.
Could you try with these?

**Comment by tomas-knap** [comment]
Tested, works
