### ISSUE TITLE
Columns with numeric cells cannot become subject columns

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#392]
In Czech:
Číslo ve sloupci ho vyřazuje jako kandidáta na “subject column”. Hodně CSV souborů
ale má svou hlavní entitu identifikovánu pomocí svého ID - čísla.

**Comment by tomas-knap** [comment]
This basically involves substantial changes to the algorithm

**Comment by tomas-knap** [comment]
User may denote certain column explicitely manually as being named entity column. 

Implication: User may then classify/disambiguate the column. Algorithm then tries to classify/disambiguate etc - considers the column as being named entity column.

**Comment by brodecva** [comment]
Hi, @josef-janousek , could you please test this on the OpenData source and file provided by the opponent?
