### ISSUE TITLE
The application uses several RDF modelling libraries and their versions

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#396]
In Czech:
SW při kompilaci stahuje 4 RDF frameworky - OpenRDF Sesame 2.7, OpenRDF
Sesame 4.0, jeho novější verzi Eclipse RDF4J a nakonec Apache Jena. Proč toto nebylo
sjednoceno?

**Comment by tomas-knap** [comment]
Just document where is used what. I guess in the core algorithm there is Jena, export uses rdf4j, UV DPU uses 2.7. I do not know why 4.0 and 2.7 is needed at the same time

**Comment by brodecva** [comment]
Partially explained and noted for improvement in https://grips.semantic-web.at/display/ADEQ/RDF+manipulation .
