### ISSUE TITLE
Task creation and primitive running UI

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#4]

**Comment by istvan-satmari** [comment]
Wrong repository set. This should be a part of "odalic/odalic-ui".

**Comment by brodecva** [comment]
Yeah, I had put the UI issues to the sti repo to keep them from harm if you decided to remove the UI repo and create it again from scratch (is was before any content was added).

Thanks for moving this one. I will close this version as it is not longer needed. Please do so yourself with the others (#23, #24, #26, #56, #25) when you have time to move them and split to more specific ones.
