### ISSUE TITLE
Extend to allow multiple subject columns

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#402]
In Czech:
Spektrum případů úspěšného použití je příliš omezené. Na rozumný výstup v RDF pro
běžné CSV tabulky nestačí, zejména pro absenci doporučování predikátů pro připojení
literálů a pro absenci možnosti generovat z jedné tabulky více typů propojených entit
(například provedená kontrola a kraj, kde byla provedena), což je celkem běžný případ.

**Comment by tomas-knap** [comment]
You can generate more entities from a table. The issue is with the datatype properties - https://github.com/odalic/sti/issues/407

**Comment by tomas-knap** [comment]
As discussed, there should be a possibility to manually define second/third subject column. In that case, if there are more subject columns, the algorithm tries to find for each such subject column relations between that subject column and other columns. 

Note: in UI, there must be a slightly different way how to select subject columns - not just one, but also more columns.

**Comment by brodecva** [comment]
Done in https://github.com/odalic/sti/pull/413 .
