### ISSUE TITLE
Create Docker image

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#403]
Propose remedies (automation, move the set up to runtime, extend documentation, provide sensible defaults)..

In Czech:Instalace a konfigurace software je časově náročná a ne zcela dostačujícím způsobem
zdokumentovaná. Zprovoznění serveru a webového klienta mi, se současnoudokumentací, zabralo 2 hodiny, a ani poté mi software nefungoval s mnou vybraným
SPARQL endpointem...

**Comment by tomas-knap** [comment]
TODO: Please specify in particular what should be done

**Comment by tomas-knap** [comment]
I would suggest to use Docker, so that you can define that you need: 

- war file for Odalic
- Solr
- config file
- Empty cache for tomcat, 
- stop words, some other resources
..

**Comment by JanVana** [comment]
Sti changes implemented in pull request #415

**Comment by brodecva** [comment]
OK for me.
