### ISSUE TITLE
Take into account the hierarchy of topics within the knowledge base (if knowledge base supports such hierarchy), so that the most concrete concept are prefered during classification

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#406]
... which improves performance and increases precision of the algorithm,

**Comment by tomas-knap** [comment]
At least hierarchy at the level of classes (e.g. for dbpedia)

**Comment by tomas-knap** [comment]
Was solved in pull request: https://github.com/odalic/sti/pull/468
