### ISSUE TITLE
Support also recommendation/adjustment of datatype properties

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#407]

**Comment by tomas-knap** [comment]
Follow up of #349

**Comment by brodecva** [comment]
@josef-janousek @tomas-knap I might need to specify in detail what is required.

**Comment by brodecva** [comment]
Hi, @tomas-knap , I have forgotten to discuss it at last meeting. Could you look at this one?

**Comment by tomas-knap** [comment]
Doesn't that work out of the box? (by a bit relaxing the requirements on predicates being returned by KBProxy?)

**Comment by tomas-knap** [comment]
Relates with https://github.com/odalic/sti/issues/391

Pls summarize here the changes needed asap, so that we can decide. 

I guess it is needed to relax KBProxy to return also datatype properties (maybe even not?). 

Related : Also when proposing new relations, it should properly safe the predicate either as Object or DataType property (for that radio button for proposing relations dialog is needed).

**Comment by brodecva** [comment]
Implemented on the server. DB file purge may be necessary.

**Comment by brodecva** [comment]
Done in the UI as of https://github.com/odalic/odalic-ui/commit/f5e35e432b567825507ce73b74dc05ab4b01b566 .
