### ISSUE TITLE
HTML version of the documentation missing

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#408]

**Comment by tomas-knap** [comment]
Github pages?

**Comment by brodecva** [comment]
@tomas-knap Found out I need a permission to export even subset of the Adequate space as HTML. As I mentioned on the Skype, could you please manage to get me one, or export it yourself, if you have it?
https://confluence.atlassian.com/conf56/exporting-confluence-pages-and-spaces-to-html-658736966.html

**Comment by brodecva** [comment]
Thank you! Downloaded. The exported docuemntation is a bit ugly, and I had to manually hide unwanted pages. Published at http://odalic.github.io.
