### ISSUE TITLE
Add minimum knowledge base WAR to Docker configuration

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#429]

**Comment by brodecva** [comment]
Separate insert endpoint implemented on the server. @istvan-satmari will add the appropriate inputs to the form in https://github.com/odalic/odalic-ui/issues/406 . So nothing stand in the way of adding this one to the docker installation (and its config to the develop may be as well).

**Comment by JanVana** [comment]
The necessary configuration changes are in the pull request #455

**Comment by JanVana** [comment]
The working docker file is here: https://github.com/odalic/odalic-docker
It should be easy to update it for the release version.

**Comment by brodecva** [comment]
Really well done!
