### ISSUE TITLE
Proposing of a class does not work

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#439]
Run the task for books-v1.csv with Dbpedia - Jan
Try to propose new class for series as follows:
![screen shot 2017-05-23 at 16 33 18](https://cloud.githubusercontent.com/assets/3014917/26359424/b7bb7fc8-3fd5-11e7-9c0d-05e48d0c1c11.png)

Tested on current develop (from yesterday)

**Comment by tomas-knap** [comment]
Does not work also for disambiguations, check also relations

**Comment by brodecva** [comment]
Fixed as of https://github.com/odalic/sti/commit/061cb117ba7be63b989d5e5e3deb8eeae6eba1e2 .
