### ISSUE TITLE
Explore UnifiedViews fitness for Implementing tasks management

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#44]
Requirements 35, 36, 38, 39, 40, 41, 42.

**Comment by tomas-knap** [comment]
As a minimum implementation, there should be UnifiedViews DPU, which is able to run Odalic conf. UV also allows us to satisfy the requirement on being able to schedule the execution. 

Specification should be prepared for that DPU. But roughly - it gets input CSV over input edge, uses the configuration (loaded from an exported conf from a file or pointing to the task conf in a running instance of Odalic?) and produces an output - should it be e.g. the export RDF/CSV or just a link to the result of Odalic task in Odalic UI?

**Comment by brodecva** [comment]
> As a minimum implementation, there should be UnifiedViews DPU, which is able to run Odalic conf. UV also allows us to satisfy the requirement on being able to schedule the execution of Odalic tasks (via using UV). 

This seems reasonable and could be relatively easily done with the API. This also provides a welcome opportunity to test the API outside of the use case of backing the UI. I will rename this task to reflect the narrowing of the issue.

**Comment by brodecva** [comment]
Duplicate.
