### ISSUE TITLE
KB configuration settings not reflected? 

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#444]
Steps: 
- I have running task, which executed successfully using dbpedia Jan (e.g. Books-v1.csv). 
- Go to KB configuration for dbpedia Jan. 
- Change the sparql endpoint URL, save
- Rerun the task
- It still ends with Success, which is a bit strange

Similarly, if I change auto-detection from Auto as follows (for dbpedia Jan): 
![screen shot 2017-05-24 at 10 58 33](https://cloud.githubusercontent.com/assets/3014917/26395339/0546633a-4070-11e7-9fb5-4a18ee7bfadc.png)

I am still getting the same result as before:
<img width="974" alt="screen shot 2017-05-24 at 10 59 27" src="https://cloud.githubusercontent.com/assets/3014917/26395385/1d58fafa-4070-11e7-86bc-688cc1313dea.png">

**Comment by tomas-knap** [comment]
It seems that it works in case of creating new task - so the issue is when "re-executing" existing one

**Comment by brodecva** [comment]
@tomas-knap Oh, stupid omission on my part. Fixed in https://github.com/odalic/sti/pull/447 .
