### ISSUE TITLE
Better error reporting - no type predicate defined

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#445]
Change settings for dbpedia Jan - groups of classes and predicates as follows: 

![screen shot 2017-05-24 at 10 58 33](https://cloud.githubusercontent.com/assets/3014917/26395339/0546633a-4070-11e7-9fb5-4a18ee7bfadc.png)

Create new task with Books-v1.csv (e.g.) and dbpedia Jan KB. 
As a result I got: 

![screen shot 2017-05-24 at 11 12 13](https://cloud.githubusercontent.com/assets/3014917/26395982/0f51e456-4072-11e7-8b4f-cf3f412dbf37.png)

Solution: I for sure should not get IllegalArgumentException!
Please check also for other cases (when type predicate is defined, but there is no label e.g.)

**Comment by brodecva** [comment]
We will discuss this with @anVana and either me or him will add a check that will verify these are present when defining the proxy.

**Comment by brodecva** [comment]
Fixed as of https://github.com/odalic/sti/commit/9c3b22f34fc92d81f295066ab9ff7a38dea2ef6e . Now the check is already done when saving the KB proxy configuration and appropriate error message appears. The overall error reporting situation, e.g. now the causing exception name is omitted, has been also improved recently.
