### ISSUE TITLE
Authorization in advanced settings

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#446]
A question: If I fill in the authorization (KB, advanced settings), does that apply to search sparql endpoint, insert sparql endpoint or both??

**Comment by brodecva** [comment]
> A question: If I fill in the authorization (KB, advanced settings), does that apply to search sparql endpoint, insert sparql endpoint or both??

It should be applied to both. There might be scenarios where the SOARQK insert endpoint might have different autorization settings, but we decided to not support it yet as there are far more pressing matters.
