### ISSUE TITLE
Knowledge bases list UI

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#45]
Requirement 51. Scenario 9.

**Comment by tomas-knap** [comment]
There should be list of knowledge bases, which users may use in the tasks - this is a must. If time, it should be also possibility to click on the knowledge base to get read-only information about that KB from config file. 

@brodecva Should be moved to UI?

**Comment by brodecva** [comment]
Duplicates #224.

**Comment by brodecva** [comment]
The UI part is kept in https://github.com/odalic/odalic-ui/issues/12 .
