### ISSUE TITLE
When exporting RDF (turtle), it opens in google excel spreadsheet

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#457]
This worked before, but now it does not work: 

![screen shot 2017-05-30 at 10 35 42](https://cloud.githubusercontent.com/assets/3014917/26575005/da90b4d4-4523-11e7-9de4-a1e2d21b959b.png)

**Comment by tomas-knap** [comment]
The same issue for JSON-LD and Annotations

**Comment by brodecva** [comment]
Duplicate of https://github.com/odalic/odalic-ui/issues/437 .
