### ISSUE TITLE
Proposing of new relations does not work - type is missing

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#459]
1) Run book-v1.csv
2) Propose new relation e.g. as below: 
![screen shot 2017-05-30 at 10 48 52](https://cloud.githubusercontent.com/assets/3014917/26575488/c502e8ce-4525-11e7-9578-4ab3ed565a60.png)

In UI everything seems OK

3) Try to search for that in the KBs - it does not show anything, so probably not correctly saved in the KB??

![screen shot 2017-05-30 at 10 48 24](https://cloud.githubusercontent.com/assets/3014917/26575494/cd6d1778-4525-11e7-91f9-2c55fa15c34d.png)

The same issue for proposing classes/disambiguations probably!!

**Comment by JanVana** [comment]
Relations are not saved to the KB. Only the proposed predicates and their attributes.

Ex:
```
select ?property ?value {<http://odalic.eu/schema/ed299429-c502-4126-9a63-8501f59a27f6> ?property ?value}
```

**Comment by tomas-knap** [comment]
Ok, yes, that is right, testing again:

Steps: 
1) Run books-v1.csv, propose new relations between series and book (e.g.). Name it "hasSeriesXX"
2) When looking into the repository, I can see: 

![screen shot 2017-05-31 at 09 10 12](https://cloud.githubusercontent.com/assets/3014917/26619973/1ab542d8-45e1-11e7-9c38-7492f38959df.png)

So the type is not correct, it should be object or datatype property.

**Comment by JanVana** [comment]
I think that you might have old/broken configuration of the main KB. Predicates for datatype and object properties seems to be set to null.

Proposing works fine on my end. Ex:
select ?property ?value {<http://odalic.eu/schema/07010368-fbbc-400b-85ca-0813e6252e42> ?property ?value}
