### ISSUE TITLE
GC Overhead limit exceeded

### ISSUE THREAD

**Issue by gobertm** [odalic/sti#474]
[text-csv.txt](https://github.com/odalic/sti/files/1299369/text-csv.txt)
Hello,

First, thank you for this great tool! 

I have a GC overhead error when executing the task of a not particularly big file. Other similar files went well. (I joined here the csv file in txt format)

Thank you,
Maxime

![image](https://user-images.githubusercontent.com/20517186/30377157-0e847ca8-988f-11e7-82f9-9ba9bf7e79e6.png)

**Comment by tomas-knap** [comment]
Hi, 

what are your memory settings for backend (task executor)?

(Sorry for a bit later response)

**Comment by tomas-knap** [comment]
Please try the develop branch again, there are quite some performance improvements now, and let me know
