### ISSUE TITLE
REST API - cannot put a file there

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#479]
When putting a file over REST API, using: 

curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer XXX" -d '{ "location": "http://example.com/files/awesome_movies_2016", "format": { "charset" : "UTF-8", "delimiter" : ";", "emptyLinesIgnored" : true, "quoteCharacter" : null, "escapeCharacter" : null, "commentMarker" : null } }' http://adequate-project-odalic.semantic-web.at/odalic/users/XXX/files/movies-test.csv

I am getting an error: 

curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer 9aaca0931e63989af4d1b0d431f51dcfc8b664ed1c970943833c59eb462d9183" -d '{ "location": "http://adequate-project-odalic.semantic-web.at/odalic/files/Books-v1.csv", "format": { "charset" : "UTF-8", "delimiter" : ";", "emptyLinesIgnored" : true, "quoteCharacter" : null, "escapeCharacter" : null, "commentMarker" : null } }' http://adequate-project-odalic.semantic-web.at/odalic/users/admin@example.com/files/movies-test.csv
{"status":400,"type":"MESSAGE","payload":{"text":"(was java.lang.UnsupportedOperationException) (through reference chain: cz.cuni.mff.xrg.odalic.api.rest.values.FileValueInput[\"format\"])","additionalResources":[],"debugContent":"com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.UnsupportedOperationException) (through reference chain: cz.cuni.mff.xrg.odalic.api.rest.values.FileValueInput[\"format\"])\n\tat com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)\n\tat com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1599)\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:278)\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)\n\tat com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)\n\tat com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)\n\tat com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:810)\n\tat org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)\n\tat org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)\n\tat org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)\n\tat org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:74)\n\tat org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)\n\tat org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)\n\tat org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)\n\tat org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:271)\n\tat org.glassfish.jersey.server.internal.inject.EntityParamValueFactoryProvider$EntityValueFactory.provide(EntityParamValueFactoryProvider.java:96)\n\tat org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.provide(ParamValueFactoryWithSource.java:71)\n\tat org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:94)\n\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:127)\n\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)\n\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)\n\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)\n\tat org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:315)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:297)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:267)\n\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)\n\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)\n\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)\n\tat org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)\n\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)\n\tat org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)\n\tat org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)\n\tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)\n\tat org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.UnsupportedOperationException\n\tat cz.cuni.mff.xrg.odalic.api.rest.adapters.FormatAdapter.unmarshal(FormatAdapter.java:18)\n\tat cz.cuni.mff.xrg.odalic.api.rest.adapters.FormatAdapter.unmarshal(FormatAdapter.java:9)\n\tat com.fasterxml.jackson.module.jaxb.AdapterConverter.convert(AdapterConverter.java:35)\n\tat com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer.convertValue(StdDelegatingDeserializer.java:237)\n\tat com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer.deserialize(StdDelegatingDeserializer.java:164)\n\tat com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)\n\tat com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)\n\t... 55 more\n"},"stamp":null}Tomas-Knaps-MacBook-Pro:etl

**Comment by tomas-knap** [comment]
Btw. how to distinguish, when using REST API, whether it is local or remote file?

**Comment by tomas-knap** [comment]
I found that when trying to unmarshall Format, there is in FormalAdapter:

  @Override
  public Format unmarshal(final FormatValue value) throws Exception {
    throw new UnsupportedOperationException();
  }

So does that mean that such operation was not implemented?

**Comment by tomas-knap** [comment]
If I create a file and then format it with a second call, it works

**Comment by brodecva** [comment]
> When putting a file over REST API, using:
> 
> curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer XXX" -d '{ "location": "http://example.com/files/awesome_movies_2016", "format": { "charset" : "UTF-8", "delimiter" : ";", "emptyLinesIgnored" : true, "quoteCharacter" : null, "escapeCharacter" : null, "commentMarker" : null } }' http://adequate-project-odalic.semantic-web.at/odalic/users/XXX/files/movies-test.csv
> 
> I am getting an error:

You are unfortunately using wrong content type, follow the latest spec in https://grips.semantic-web.at/display/ADEQ/REST+API+specification .

> I found that when trying to unmarshall Format, there is in FormalAdapter:
> 
> @override
> public Format unmarshal(final FormatValue value) throws Exception {
> throw new UnsupportedOperationException();
> }
> 
> So does that mean that such operation was not implemented?

What it means is that the adapter is not used to unmarshall the FormatValue (aka the object passed from user to the server) to domain Format object, and the unmarshalling is instead done manually in appropriate resource methods. The original reason being that the Format object holds information about line separator, which the user is not burdened to provide in JSON input mapped to FormatValue (the algorithm is able to reliably detect it from the input). You can see in cz.cuni.mff.xrg.odalic.api.rest.resources.FormatResource , that the FormatValue is directly used as parameter of the methods, instead of usual domain objects (which are silently marshalled and unmarshalled). This workaround is also used in other cases where the adapters are more trouble than they are worth (e.g. the unmarshalled domain object needs some additional info from the database, or the adapter would have some dependencies which are practically impossible to inject to adapter objects).

**Comment by tomas-knap** [comment]
Thanks, solved that by using two calls - one to put the file there, second to set format (if needed). Also UI works with services in that way.

**Comment by tomas-knap** [comment]
One note: The downside of https://grips.semantic-web.at/display/ADEQ/REST+API is that there are no examples as e.g. at https://grips.semantic-web.at/pages/viewpage.action?pageId=76228328
