### ISSUE TITLE
Add restricted task REST API

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#5]
Add to the REST API project methods supporting the task creation a running UI. When encountering not yet specified part, substitute it with a mock, empty implementation or other suitable concept. 
Do no implement any of the methods. Let them call a suitable interface from a new project in the repository (feel free to add it in such way that it can refer to the methods of the core), where we will put  our extensions to the core (mainly task, file, and other kinds of resource management).

**Comment by istvan-satmari** [comment]
Could you be more specific...? Thanks :)

**Comment by brodecva** [comment]
Sorry about that. Just learning to work with Github issues and waffle.io. Description added. If you feel it is still to vague or that there are still some things unspecified, please do tell us.
