### ISSUE TITLE
Relation establishing component

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#56]
Should in engaging way (for example visually connecting the columns) enable the creation or changing of relations. Should include predicate browsing, searching and selecting component similar to the one from issue #25 (this feature can be also mocked for the 1st iteration).

**Comment by istvan-satmari** [comment]
- Probably will be very primitively represented via a table (table of relations).
- "predicate browsing, searching and selecting component" seems complicated. Please specify.
- BTW, see my question in (25) about how the feedback matters for the first iteration?

**Comment by brodecva** [comment]
I recommend to do some short research if there is not some existing compatible visual component that would provide us with this functionality. If not, than it is understandable that some simple table representation will do.

I went into more detail in the answer for #25, the concept searching part of this component is more-or-less the same. The difference is, that is this one also provides means to connect the columns.

Question in #25 seen and answered.

**Comment by brodecva** [comment]
Also notice that #63 covers providing the interface to the KB on the server, so communicate with the assignee of this issue when the time comes.

**Comment by brodecva** [comment]
Deprecated.
