### ISSUE TITLE
Allow import to knowledge bases form SPARQL endpoint

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#58]
Should only generalise the code created for #1.

**Comment by tomas-knap** [comment]
What is the particular idea of this task?

**Comment by brodecva** [comment]
> What is the particular idea of this task?

As I understand it, in times where we envisioned a much richer KB management, this feature would allow to import content from other SPARQL bases into our own. Which seems bit convoluted now. I will mark it wontfix, unless you are against it.
