### ISSUE TITLE
Replace Xtractor implementation with reliable, robust and capable CSV parsing library

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#6]
The current implementation is very crude and lacks configuration options and is of sub-par quality. it also relies on temporary files as input (the ideal implementation should have no trouble to parse input stream of a string).
Replace it with an external library of your choosing that is reliable, robust and capable to meet the requirements and scenario description. its features must cover the extent of input specification in the CSV meta-data (see https://www.w3.org/2013/csvw/wiki/Main_Page for specification and http://data.opendataportal.at/dataset/kunstler-der-sammlung-des-mumok/resource/e25640f8-a3e4-46d2-8a4f-9be471b115d2 for example).
The parsed result should be available as Input interface instance (already provided, together with incomplete SimpleInput implementation). Do the parsing with your library in provided DefaultCsvInputParser (add more methods, for input stream, for example, if you wish).

**Comment by JanVana** [comment]
Should be functional.
