### ISSUE TITLE
Inspect solr exceptions thrown during algorithm run

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#83]
...and fix them if possible. I am not concerned about any connections timeouts and so, but the errors reported when the solr attempts to write something.

**Comment by JanVana** [comment]
I would like to give this issue more time, so do not close it yet, please.

**Comment by JanVana** [comment]
Ok, the caches initialization has been reworked in the task #115. Can you check if you still see these warnings?

**Comment by brodecva** [comment]
The exceptions disappeared.
