### ISSUE TITLE
Enable multiple KB configuration (static)

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#91]
See https://grips.semantic-web.at/x/cYVlB for details.

**Comment by tomas-knap** [comment]
Please do not forget to also adjust the sample config files. I cannot see any adjustments to https://github.com/odalic/sti/blob/develop/config/kbsearch.properties

**Comment by brodecva** [comment]
> Please do not forget to also adjust the sample config files. I cannot see any adjustments to https://github.com/odalic/sti/blob/develop/config/kbsearch.properties

Maybe I was not clear enough. I have checked out the newst branch with modifications by @JanVana from https://github.com/odalic/sti/pull/107 . It seems fine to me and does contain the mentioned adjustments. But I have to yet accept the pull request to develop and I will do so as soon as possible (after today Skype meeting and maybe some additional tests).

**Comment by brodecva** [comment]
Postponed until 2016-10-08 to allow some polishing of the code.
