### ISSUE TITLE
Remove any23-sti extensions, use standard any23 library if such library is really needed

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#93]
There is any23-sti module, which defines extension for any23 library. Nevertheless, the question is whether we need such extensions. 
1. As discussed with Ziqi, such extension was done so that he can get xpath of the extracted RDFa triples. But such features was not used at the end
2. This library is used by TableContextExtractorIMDB and TableContextExtractorMusicBrainz classes in core to extract RDFa triples from the websites (and thus to have further context for the table). Nevertheless we do not try to extract any table from the Web. 

The goal is to remove any23-sti module and if needed in the future, we may try to use the standard distribution first.

**Comment by brodecva** [comment]
Removed as of https://github.com/odalic/sti/commit/23bd891df68e50569529062ea2939b5d60c86870 . Closing.
